# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Verifica el código
      - uses: actions/checkout@v4
      
      # Habilita Corepack
      - run: corepack enable
      
      # Configura Node.js y habilita caché para PNPM
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      # Instala PNPM y las dependencias
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: pnpm install

      # Construye el proyecto para GitHub Pages
      - run: pnpx nuxt build --preset github_pages

      # Sube los artefactos generados
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    needs: build
    permissions:
      pages: write      # Permiso para desplegar en GitHub Pages
      id-token: write   # Permiso para validar el origen del despliegue
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Despliega a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
